{{- if .Values.app.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dsipsmule-voter.fullname" . }}-pvc
  labels:
    {{- include "dsipsmule-voter.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.app.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.app.storage.size }}
  {{- if .Values.app.storage.storageClass }}
  storageClassName: {{ .Values.app.storage.storageClass }}
  {{- end }}
{{- end }}
