apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dsipsmule-voter.fullname" . }}-env
  labels:
    {{- include "dsipsmule-voter.labels" . | nindent 4 }}
type: Opaque
stringData:
  SESSION_SECRET: {{ .Values.app.sessionSecret | quote }}
  TELEGRAM_BOT_USERNAME: {{ .Values.app.telegramBotUsername | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.app.telegramBotToken | quote }}
  ADMIN_USERNAME: {{ .Values.app.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.app.adminPassword | quote }}
